name: as3438_m2cw
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - accelerate=0.27.2
  - ipykernel==6.29.2
  - ipython==8.21.0
  - numpy==1.26.4
  - tqdm==4.66.2
  - pip
  - pip:
    - torch==2.2.0
    - torchvision==0.17.0



